version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5433:5432'
    container_name: 'pgsql-ImoBanco'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

volumes:
  pg-data: